#!/bin/sh

# ATC 5401 API Reference Implementation Project 
# 
#     Filename: runAPIVS
#    File Type: Linux shell script
#    Test Case: many
#  Description: run VSE from USB at startup on specific test cases
#               
# Date      Revision    Description
# 2/24/16   1.0         initial release

# start async loopback driver; add symbolic links
insmod /media/sda1/APIVS/bin/tty0tty.ko
ln -s /dev/tnt0 /dev/sp6_loopback_a
ln -s /dev/tnt1 /dev/sp6_loopback_b

# start the API Front Panel Manager (loopback mode)
modprobe front_panel
FrontPanelManager /dev/sp6_loopback_a 1>/dev/null 2>&1 &
MasterSelection 1>/dev/null 2>&1 &

# start sync loopback driver; fio driver; add symbolic links
rmmod fiodriver
insmod /media/sda1/APIVS/bin/virtual-loopback-sync.ko
insmod /media/sda1/APIVS/bin/fiodriver.ko apivs=1
ln -s /dev/vlsync0 /dev/sp3s_loopback_a
ln -s /dev/vlsync1 /dev/sp3s_loopback_b
ln -s /dev/vlsync2 /dev/sp5s_loopback_a
ln -s /dev/vlsync3 /dev/sp5s_loopback_b
ln -s /dev/vlsync4 /dev/sp8s_loopback_a
ln -s /dev/vlsync5 /dev/sp8s_loopback_b

# initialize test counters
pass_count=0
fail_count=0

# a couple of useful subroutines
clear_test_line() {
   printf "\x1B[3;1f" >/dev/sp6
   printf "                                        " >/dev/sp6
   printf "\x1B[3;1f" >/dev/sp6
}
print_test_result() {
   if [ "$?" == "0" ]; then
      printf "PASS" >/dev/sp6
      pass_count=$((pass_count + 1))
      else
      printf "FAIL" >/dev/sp6
      fail_count=$((fail_count + 1)); fi
   printf "\x1B[8;1f" >/dev/sp6
   printf "Test cases passed:%d failed:%d" "$pass_count" "$fail_count" >/dev/sp6
#  keep backlight on
   printf "\033[<5h" >/dev/sp6
   sleep 1
}
reset_modules() {
#  start the API Front Panel Manager (loopback mode)
   killall MasterSelection
   killall FrontPanelManager
   rmmod front_panel
   modprobe front_panel
   FrontPanelManager /dev/sp6_loopback_a 1>/dev/null 2>&1 &
   MasterSelection 1>/dev/null 2>&1 &
#  start fio driver
   rmmod fiodriver
   insmod /media/sda1/APIVS/bin/fiodriver.ko apivs=1
}
misc_test_C6020() {
   #Check for uClibc load object identifier (APIVS[3.8])
   LD_TRACE_LOADED_OBJECTS=1 vse | grep -q "ld-uClibc"
   if [ $? != 0 ]
   then
        echo "$(date -u): vse is not compatible with uClibc" >/tmp/C6020_log.txt
        retval=1
   else
        echo "$(date -u): vse is compatible with uClibc" >/tmp/C6020_log.txt
        retval=0
   fi
   mv /tmp/C6020_log.txt ./
   sync
   return $retval
}
misc_test_C6030() {
   #Check for ELF format (APIR3.5.2[5])
   elfmagic="7f454c46"

   FILES="/usr/lib/libfpui.so
   /usr/lib/libfio.so
   /usr/lib/libtod.so"

   for f in $FILES
   do
   if [ $(od -An -N4 -tx4 <$f) == $elfmagic ]; then
      echo "$(date -u): $f is ELF format file" >>/tmp/C6030_log.txt
      retval=0
   else
      echo "$(date -u): $f is not ELF format file" >>/tmp/C6030_log.txt
      retval=1
   fi
   done
   mv /tmp/C6030_log.txt ./
   sync
   return $retval
}

# set the conformance level this run (1,2,3)
LEVEL=3

# delete old log files? (FALSE will append if exists)
DELETE_LOGS=TRUE

# how many times to run?
loop_count=1

# loop through all specified test cases
while [ $loop_count -ge 1 ]
do
   if [ "$DELETE_LOGS" == TRUE ]; then rm C1310_log.xml; fi
   clear_test_line; printf "Testing APIVS.TCS.1310... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C1310_in.xml -o C1310_log.xml
   print_test_result
   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C1320_log.xml; fi
   clear_test_line; printf "Testing APIVS.TCS.1320... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C1320_in.xml -o C1320_log.xml
   print_test_result
   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C1330_log.xml; fi
   clear_test_line; printf "Testing APIVS.TCS.1330... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C1330_in.xml -o C1330_log.xml
   print_test_result
   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C1350_log.xml; fi
   clear_test_line; printf "Testing APIVS.TCS.1350... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C1350_in.xml -o C1350_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2010_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2010... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2010_in.xml -o C2010_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2020_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2020... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2020_in.xml -o C2020_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2030_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2030... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2030_in.xml -o C2030_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2040_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2040... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2040_in.xml -o C2040_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2050_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2050... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2050_in.xml -o C2050_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2070_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2070... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2070_in.xml -o C2070_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2080_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2080... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2080_in.xml -o C2080_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2090_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2090... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2090_in.xml -o C2090_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C2100_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.2100... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C2100_in.xml -o C2100_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3010_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3010... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3010_in.xml -o C3010_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3020_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3020... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3020_in.xml -o C3020_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3030_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3030... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3030_in.xml -o C3030_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3040_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3040... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3040_in.xml -o C3040_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3050_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3050... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3050_in.xml -o C3050_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3060_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3060... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3060_in.xml -o C3060_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3070_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3070... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3070_in.xml -o C3070_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3080_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3080... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3080_in.xml -o C3080_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3090_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3090... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3090_in.xml -o C3090_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3100_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3100... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3100_in.xml -o C3100_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3110_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3110... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3110_in.xml -o C3110_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3120_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3120... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3120_in.xml -o C3120_log.xml
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C3130_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.3130... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C3130_in.xml -o C3130_log.xml
   print_test_result

   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C6010_log.xml; fi
   clear_test_line; printf "Testing APIRI.TCS.6010... " >/dev/sp6
   vse -L $LEVEL -c ./VS_config_1.txt -i C6010_in.xml -o C6010_log.xml
   print_test_result

   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C6020_log.txt; fi
   clear_test_line; printf "Testing APIRI.TCS.6020... " >/dev/sp6
   misc_test_C6020
   print_test_result
   
   reset_modules   
   if [ "$DELETE_LOGS" == TRUE ]; then rm C6030_log.txt; fi
   clear_test_line; printf "Testing APIRI.TCS.6030... " >/dev/sp6
   misc_test_C6030
   print_test_result   
      
   mv /tmp/*log.xml ./
   sync
   
   loop_count=$((loop_count - 1))
done
